### ISSUE TITLE
Nodeserver did not restart after reboot of 994 isy

### ISSUE THREAD

**Issue by SteveHoyt** [UniversalDevicesInc-PG3/udi-poly-FlumeWater#4]
just had to reboot my 994 isy for another reason. The flume node server did not restart automatically. I had to manually reboot. Log file included if you think it needs to be looked at
[FlumeWater_2-10-2022_91757_AM.txt](https://github.com/UniversalDevicesInc-PG3/udi-poly-FlumeWater/files/8042992/FlumeWater_2-10-2022_91757_AM.txt)
.

**Comment by jimboca** [comment]
The nodeserver had crashed prior to that due to the bug that I fixed in 3.0.6:
```
2022-02-10 08:31:23,075 Command    udi_interface      ERROR    udi_interface:write: Exception in thread
2022-02-10 08:31:23,076 Command    udi_interface      ERROR    udi_interface:write: Command
2022-02-10 08:31:23,077 Command    udi_interface      ERROR    udi_interface:write: :
2022-02-10 08:31:23,078 Command    udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-02-10 08:31:23,078 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-02-10 08:31:23,083 Command    udi_interface      ERROR    udi_interface:write: self.run()
2022-02-10 08:31:23,084 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.8/threading.py", line 870, in run
2022-02-10 08:31:23,088 Command    udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-02-10 08:31:23,089 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/interface.py", line 647, in _parseInput
2022-02-10 08:31:23,095 Command    udi_interface      ERROR    udi_interface:write: self._handleInput(key, input[key], None)
2022-02-10 08:31:23,096 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/interface.py", line 774, in _handleInput
2022-02-10 08:31:23,100 Command    udi_interface      ERROR    udi_interface:write: self.nodes_internal[item['address']].query()
2022-02-10 08:31:23,101 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/00:21:b9:02:17:0e_11/nodes/Controller.py", line 68, in query
2022-02-10 08:31:23,104 Command    udi_interface      ERROR    udi_interface:write: self.nodes[node].reportDrivers()
2022-02-10 08:31:23,105 Command    udi_interface      ERROR    udi_interface:write: AttributeError
2022-02-10 08:31:23,105 Command    udi_interface      ERROR    udi_interface:write: :
2022-02-10 08:31:23,106 Command    udi_interface      ERROR    udi_interface:write: 'Controller' object has no attribute 'nodes'
```
